name: Build Android
on: push
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip Project
        run: |
          unzip FISH_it_ultimate_v6.zip
          rm FISH_it_ultimate_v6.zip
      
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.2.1
          
      - name: Export
        run: |
          mkdir build
          godot --headless --export-release "Android" build/FISH_IT_V6.apk
          
      - uses: actions/upload-artifact@v4
        with:
          name: APK-FISH-IT
          path: build/FISH_IT_V6.apk
